version: '3.6'
services:
  postgres:
    container_name: postgres_db
    image: postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=abry

  node_app:
    container_name: node_app
    build:
      context: .
      dockerfile: node.Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - 'postgres'

  graphql-engine:
    container_name: graphql_engine
    image: hasura/graphql-engine:v2.18.0
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'

volumes:
  db_data:
