version: '3.6'
services:
  node_app:
    build:
      args:
        - NODE_ENV=production

    environment:
      - PORT=3000
      - NODE_ENV=production

    command: node ./src/index.js

  graphql-engine:
    env_file:
      - ./production.env
